name: e_commerce_clothing_store
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  carousel_slider: ^4.2.1
  smooth_page_indicator: ^1.2.0+3
  flutter_carousel_widget: ^2.1.2
  http: ^1.2.2
  provider: ^6.0.5
  firebase_core: ^3.10.0    
  firebase_auth: ^5.3.2
  cloud_firestore: ^5.6.1
  cupertino_icons: ^1.0.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
