// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5lbrOv3mxMMPSRabSw8t4Bf96jtxhwps',
    appId: '1:446861035427:web:6a9a47e50cb58979443c16',
    messagingSenderId: '446861035427',
    projectId: 'ecommerce-capstone-807ce',
    authDomain: 'ecommerce-capstone-807ce.firebaseapp.com',
    storageBucket: 'ecommerce-capstone-807ce.firebasestorage.app',
    measurementId: 'G-GKJX1MVVRX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfD7s9J7W4l8aMG1OUC3vRcxRWDfSFK1w',
    appId: '1:446861035427:android:040e446e93f95705443c16',
    messagingSenderId: '446861035427',
    projectId: 'ecommerce-capstone-807ce',
    storageBucket: 'ecommerce-capstone-807ce.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSeAt3921NvVzqutC0AHHOYPpIB8LqAhM',
    appId: '1:446861035427:ios:af63aefac82de1e3443c16',
    messagingSenderId: '446861035427',
    projectId: 'ecommerce-capstone-807ce',
    storageBucket: 'ecommerce-capstone-807ce.firebasestorage.app',
    iosBundleId: 'com.example.eCommerceClothingStore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSeAt3921NvVzqutC0AHHOYPpIB8LqAhM',
    appId: '1:446861035427:ios:af63aefac82de1e3443c16',
    messagingSenderId: '446861035427',
    projectId: 'ecommerce-capstone-807ce',
    storageBucket: 'ecommerce-capstone-807ce.firebasestorage.app',
    iosBundleId: 'com.example.eCommerceClothingStore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5lbrOv3mxMMPSRabSw8t4Bf96jtxhwps',
    appId: '1:446861035427:web:670d3f12222f9094443c16',
    messagingSenderId: '446861035427',
    projectId: 'ecommerce-capstone-807ce',
    authDomain: 'ecommerce-capstone-807ce.firebaseapp.com',
    storageBucket: 'ecommerce-capstone-807ce.firebasestorage.app',
    measurementId: 'G-HQ6118C5PP',
  );
}
